### PR TITLE
Update .upptimerc.yml

### PR DESCRIPTION
**Pull request by LinuxMeow**

### CODE REVIEW

**Comment by unixfox** [comment]
Can you explain why you want this instance to be manually tracked?

**Comment by LinuxMeow** [comment]
What do you mean by manually? Isn't it automated process?

Just wanted to always have quick reference to how my node performs from external server location that's all. Just tracking purposes really.

**Comment by unixfox** [comment]
Well this repository is for automatically tracking new searx instances that are added to the public list: https://github.com/searxng/searx-instances

We don't usually allow to manually add an instance to the public uptime tracker.

**Comment by LinuxMeow** [comment]
Didn't it say at the bottom of the public listing repo that if you do not want to add it to public list go here? I want to monitor my server and configure my proxy and load balancer first and make it secure before I just add it to public list repo. Am I missing something? I am sorry.

**Comment by LinuxMeow** [comment]
image

[https://github.com/searxng/searx-instances](https://github.com/searxng/searx-instances)

**Comment by unixfox** [comment]
> image
> 
> [searxng/searx-instances#add-a-new-instance-to-be-tracked-for-their-uptime-without-adding-it-on-the-public-list](https://github.com/searxng/searx-instances#add-a-new-instance-to-be-tracked-for-their-uptime-without-adding-it-on-the-public-list)

Oh that, it's a notice for the maintainers of the public list to manually add instances to the uptime tracker. Not really for anyone to add his own instance.

Anyway that's fine for me, we can track the uptime of your instance. I just added it here: https://github.com/searxng/searx-instances-uptime/commit/c26182d0866a9fd3151652b6d086653a984a7d0b

**Comment by LinuxMeow** [comment]
Sure thing. I will have to spin up replicas do nginx proxy load balancing and hardening rather than just spinning it up. It will take day or two, Will let you know when. Thanks and sorry.

**Comment by LinuxMeow** [comment]
Hey, I've seen some numbers on status page. May I know where are you monitoring from?

Compared to my data here it reports like 12 or 13 times higher request time than my own tracker.

**Comment by unixfox** [comment]
It's from USA: https://github.com/orgs/community/discussions/24969#discussioncomment-3246032

We are using github actions for that.

**Comment by LinuxMeow** [comment]
I see now it makes sense. Hey mate thanks for help, I got numbers from external source as I mentioned as a reason for the add. You can remove my instance now if you want, I will spin some servers up around the EU and do more monitoring from servers closer now as well.

Thank you for helping out. Once I set up my server and decide to publish it as public I will let you know in the other project that is related to this.

Thanks again.

**Pull request closed without merging**
